### ISSUE TITLE
Server does not run on Gitlab CI

### ISSUE THREAD

**Issue by theSage21** [aio-libs/aiohttp#2702]
## Long story short

Server does not run on Gitlab CI

## Expected behaviour

When issuing the command `pipenv run python server.py &` the server should start and run in both my local machine and in the Gitlab CI environment.

## Actual behaviour

The server only runs in my local machine and in the gitlab CI machine does not connect to the required port.

## Steps to reproduce

I have set up a demonstration project at <https://gitlab.com/theSage21/AIO-CI-TEST>.
To run locally:

```bash
pipenv install
pipenv run python server.py
```

To run on gitlab, simply make changes and push to gitlab. The failed CI log can be seen at <https://gitlab.com/theSage21/AIO-CI-TEST/-/jobs/50624691>

The gitlab CI file has the following structure.

```yaml
test_server_api:
    image: "python:3.6"
    variables:
        MONGO_URI: "mongodb://mongo/exchange"
    services:
        - mongo
    before_script:
        - pip install pipenv
        - pipenv install --ignore-pipfile --dev
    script:
        - "pipenv run python server.py &"
        - "until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:8000); do printf '.'; sleep 5; done"
    stage: test
```

The `curl` loop in the end waits for the socket to be made available.

## Your environment
I'm using python 3.6 and aiohttp 2.3.9
The environment is created and managed by `pipenv` so I don't think that should be a problem.
